import { http, HttpResponse } from 'msw'
import { makeBrowse, makeNotes, makeProgress, makeStateMatrix, makeSeg, makeClipInfo, makeTranscriptFix, makeMeta, makeClockState, makeTrackOverview, makeWhoState, makeMusicState, makeStudioState, makeStudioPreview, makeEditResponse, makeScript2State, makeScriptState, makeVoiceoverState, makeTrackLine, makeTracksListing, makeTrackSeries, makeTrackClip, makeClipDetail, makeFilmState, makeStillState, makeStillList, makeFinalState, makeRoughMix, makeLyrics } from './factories'

// Default happy-path handlers, one per endpoint. Only the endpoints the tests so far need are here: when a test hits an endpoint that is missing,
// msw fails it loudly (onUnhandledFrame: 'error'), so add the handler here (with a factory in factories.ts) rather than inline in the test.
// Per-test variations belong in the test, via `mockGet`/`mockPost`/`mockError` from ./api.
export const handlers = [
  http.get('/api/last', () => HttpResponse.json({ folder: null })),
  http.get('/api/browse', () => HttpResponse.json(makeBrowse())),
  http.get('/api/notes', () => HttpResponse.json(makeNotes())),
  http.post('/api/notes', async ({ request }) => HttpResponse.json(makeNotes({ folder: ((await request.json()) as { text: string }).text }))),
  http.post('/api/open', () => HttpResponse.json({ started: true })),
  http.get('/api/progress', () => HttpResponse.json(makeProgress())),
  http.get('/api/log', () => HttpResponse.json({ lines: [] })),
  http.get('/api/coverage', () => HttpResponse.json({ clips: 0, stages: [], totals: {}, blocked: {}, missing: [], complete: true })),
  http.get('/api/state', () => HttpResponse.json(makeStateMatrix())),
  http.post('/api/run', () => HttpResponse.json({ started: true })),
  http.post('/api/stop', () => HttpResponse.json({ stopped: 1 })),
  http.post('/api/clear', () => HttpResponse.json({ cleared: 1 })),
  http.get('/api/transcript', () => HttpResponse.json({ segments: [makeSeg()] })),
  http.get('/api/transcript/suggest', () => HttpResponse.json(makeTranscriptFix())),
  http.post('/api/transcript/suggest', () => HttpResponse.json({ started: true })),
  http.post('/api/transcript/edit', () => HttpResponse.json({ ok: true })),
  http.get('/api/clips', () => HttpResponse.json({ clips: [makeClipInfo()] })),
  http.get('/api/meta', () => HttpResponse.json(makeMeta())),
  http.get('/api/clock', () => HttpResponse.json(makeClockState())),
  http.post('/api/clock', () => HttpResponse.json({ clock: makeClockState(), retimed: 1 })),
  http.get('/api/clock/suggest', () => HttpResponse.json({ current: 0, suggestions: [] })),
  http.get('/api/track', () => HttpResponse.json(makeTrackOverview())),
  http.post('/api/track', () => HttpResponse.json(makeTrackOverview({ present: true, file: 'track.fit' }))),
  http.get('/api/who', () => HttpResponse.json(makeWhoState())),
  http.post('/api/who', () => HttpResponse.json({ ok: true })),
  http.get('/api/tracks', () => HttpResponse.json(makeTracksListing())),
  http.get('/api/tracks/line', ({ request }) => HttpResponse.json({ id: new URL(request.url).searchParams.get('id'), lat: [50.0, 50.001], lon: [5.0, 5.001] })),
  http.get('/api/track/line', () => HttpResponse.json(makeTrackLine())),
  http.get('/api/track/series', () => HttpResponse.json(makeTrackSeries())),
  http.post('/api/meta', async ({ request }) => HttpResponse.json(makeMeta(await request.json() as any))),
  http.get('/api/film', () => HttpResponse.json(makeFilmState())),
  http.post('/api/film/start', () => HttpResponse.json({ started: true })),
  http.post('/api/film/stop', () => HttpResponse.json({ ok: true })),
  http.get('/api/film/stills', () => HttpResponse.json(makeStillList())),
  http.post('/api/film/still', () => HttpResponse.json(makeStillState())),
  http.get('/api/film/still', () => HttpResponse.json(makeStillState({ state: 'done' }))),
  http.get('/api/final', () => HttpResponse.json(makeFinalState())),
  http.post('/api/final/start', () => HttpResponse.json({ started: true })),
  http.post('/api/final/stop', () => HttpResponse.json({ ok: true })),
  http.get('/api/script2/mix', () => HttpResponse.json(makeRoughMix({ has_plan: false }))),
  http.get('/api/tiles/status', () => HttpResponse.json({ ok: true, style: 'tf-landscape', error: '', credit: 'Maps © Thunderforest, data © OpenStreetMap contributors', tile_px: 512 })),
  http.get('/api/lyrics', () => HttpResponse.json(makeLyrics({ has_track: false }))),
  http.get('/api/photos', () => HttpResponse.json({ photos: [], tz: 'Europe/Brussels' })),
  http.get('/api/gaps', () => HttpResponse.json({ gaps: [] })),
  http.get('/api/streetview/chosen', () => HttpResponse.json({ sections: [] })),
  http.get('/api/streetview/video', () => HttpResponse.json({ exists: false, running: false, log: [], error: '', seconds: 12 })),
  http.get('/api/track/clips', () => HttpResponse.json({ clips: [makeTrackClip()], has_draft: true })),
  http.get('/api/script2', () => HttpResponse.json(makeScript2State())),
  http.post('/api/script2/pins', async ({ request }) => HttpResponse.json(await request.json())),
  http.post('/api/script2/plan', () => HttpResponse.json({ started: true })),
  http.post('/api/script2/generate', () => HttpResponse.json({ started: true })),
  http.post('/api/transcript/mark', () => HttpResponse.json({ ok: true, marked: 0 })),
  http.get('/api/music', () => HttpResponse.json(makeMusicState())),
  http.post('/api/music', () => HttpResponse.json(makeMusicState({ file: 'track.mp3' }))),
  http.delete('/api/music', () => HttpResponse.json({ ok: true })),
  http.get('/api/music/studio', () => HttpResponse.json(makeStudioState())),
  http.post('/api/music/studio/analyse', () => HttpResponse.json(makeStudioState())),
  http.post('/api/music/studio/preview', () => HttpResponse.json(makeStudioPreview())),
  http.post('/api/music/studio/build', () => HttpResponse.json({ started: true })),
  http.get('/api/edit', () => HttpResponse.json(makeEditResponse())),
  http.post('/api/edit/propose', () => HttpResponse.json({ edit: makeEditResponse().edit })),
  http.post('/api/edit/override', () => HttpResponse.json({ edit: makeEditResponse().edit })),
  http.get('/api/script', () => HttpResponse.json(makeScriptState())),
  http.post('/api/llm/key', () => HttpResponse.json({ configured: true })),
  http.post('/api/script/generate', () => HttpResponse.json({ started: true })),
  http.post('/api/script/edit', () => HttpResponse.json({ saved: 'saved', speaking: true })),
  http.get('/api/voiceover', () => HttpResponse.json(makeVoiceoverState())),
  http.post('/api/voiceover/build', () => HttpResponse.json({ started: true })),
  http.post('/api/voiceover/use', () => HttpResponse.json({ ok: true })),
  http.post('/api/voiceover/record', () => HttpResponse.json({ ok: true })),
  http.delete('/api/voiceover/record', () => HttpResponse.json({ ok: true }))
]
export const extraHandlers = [
  http.get('/api/clip', () => HttpResponse.json(makeClipDetail())),
  http.post('/api/clip/object/hide', () => HttpResponse.json({ ok: true })),
]

handlers.push(...extraHandlers)
